add round-trip serde for prc/pdb and tests
u1f408/palmrs pull request #1
Opened 2023-06-27 02:18 UTC by knickish

Tiny bit of cleanup, and lots of changes to the serialization and deserialization code with tests to match. Can now load and then output a byte-for-byte matching pdb/prc for all the examples already in the repo.

2023-06-27 02:48 UTC, u1f408 commented
Hey, thanks for the PR! I'll look at this properly in the next couple days, but from a quick glance this looks great :)

2023-06-27 03:15 UTC, knickish commented
Sounds good! Planning to work on this quite a bit over the next couple months, will try to upstream what I can

2023-06-28 03:07 UTC, u1f408 requested changes
Looks great! My only real nitpick is the `dbg!()` calls you've left scattered in there, other than that I'm happy to merge this :)

2023-06-28 03:07 UTC, u1f408 commented on palmrs-database/src/info/category.rs
> +		}
remove `dbg!()` calls

2023-06-28 03:07 UTC, u1f408 commented on palmrs-database/tests/format_pdb_palmdoc.rs
> +	let header = dbg!(DatabaseHeader::from_bytes(&EXAMPLE_PDB).unwrap());
and here (not _as_ important bc this is only in a test, but...)

2023-06-28 03:07 UTC, u1f408 commented on palmrs-database/tests/format_pdb_tododb.rs
> +	// dbg!(&database);
and here

2023-06-28 03:11 UTC, knickish commented
I think I got them all. Was one more you hadn't listed here that I'd missed also.

2023-06-28 03:20 UTC, u1f408 approved these changes

2023-06-28 03:20 UTC, merged

2023-06-28 03:21 UTC, u1f408 commented
Thanks heaps! 😸

2023-06-28 03:24 UTC, knickish commented
Of course! This repo saved me so much time, thought I was going to have to do it from scratch.